name: netflix_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  http: ^1.2.0
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^3.0.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true
