name: netflix_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/images/
  uses-material-design: true
  